### ISSUE TITLE
Use a hex color as "base_color"

### ISSUE THREAD

**Issue by MaximeWillinger** [Fooidge/PleaseJS#13]
Hi !

It would be great  to add the ability to use a color in hex as "base_color".

Example : 

``` javascript
Please.make_color({
      base_color: '#FF0000'
});
```

**Comment by MaximeWillinger** [comment]
EDIT : I made a pull request that need some reviews : https://github.com/Fooidge/PleaseJS/pull/15

**Comment by spherop** [comment]
i assumed that this was the default functionality! ... huge +1.

**Comment by sircelsius** [comment]
I totally agree. I wish it were implemented, the possibilities would truly be endless then.

**Comment by MaximeWillinger** [comment]
There is a pending pull request (https://github.com/Fooidge/PleaseJS/pull/16), you can contribute :)

**Comment by Fooidge** [comment]
Fixed!
