### ISSUE TITLE
Seed support

### ISSUE THREAD

**Issue by MaciekBaron** [Fooidge/PleaseJS#3]
It would be nice if the library supported colours generated based on a seed.

I can give this a go later this week if you're interested.

**Comment by Fooidge** [comment]
Do you mean a seed color? Or seeding the randomization?

**Comment by MaciekBaron** [comment]
Seeding the randomisation; this could be done by implementing something like a RC4 pseudo-random number generation ([here](https://github.com/MaciekBaron/BMLTrafficJS/blob/master/js/rc4random.js) is an implementation of it I've done for a different project).

What I have in mind is the ability to generate a set of colours based on selected parameters and a seed (e.g. a string), which would always return the same colour for the same string.

**Comment by Fooidge** [comment]
Can you give me an example of a compelling use for this?

**Comment by MaciekBaron** [comment]
For instance, you can generate a set of colours based on a nickname etc.. It's useful for situations when you want to have the same colour scheme for a seed (e.g. nickname) but you don't want to store the generated colours anywhere. All you need to do is read the nickname and retrieve the set of colours you have generated.

Another example, in procedurally generated games you might want to generate some colour schemes. The procedural generation could be seed based, and you always want to have the same output/result for the same seed.

**Comment by Fooidge** [comment]
Give it a whack, seems cool. My main concern is the size to benefit ratio of this change.

**Comment by MaciekBaron** [comment]
It will be just a few lines of modifications to the existing code plus the implementation of RC4, which is little over 40 lines and can be improved. I'll give it a go this weekend.

**Comment by NadyaNayme** [comment]
@Fooidge 
This actually sounds pretty cool and would add a layer of sociability between users of PleaseJS. 

For example, I could tweet:
"Check out 'Fudge'! It's absolutely delicious! #PleaseJS"

[Random passerby comment]

**Comment by Fooidge** [comment]
Except 'Fudge' might be magenta. But I am sort of geeking already at the thought of having a hashtag for this.

**Comment by NadyaNayme** [comment]
I see no harm in Fudge being magenta. 
Just hope Fooidge isn't pink? ;)

**Comment by alexhulbert** [comment]
:+1: Amazing library, by the way. This is by far the best color generation module I've ever seen.

**Comment by Fooidge** [comment]
No. Was gonna look at it tomorrow. 

Jordan Checkman

**Comment by Fooidge** [comment]
Added in https://github.com/Fooidge/PleaseJS/commit/1482cad71498a61601954b720df83bfc7cee1cac
