### ISSUE TITLE
make_color has inconsistent return type

### ISSUE THREAD

**Issue by ixtli** [Fooidge/PleaseJS#34]
https://github.com/Fooidge/PleaseJS/blob/master/Please.js#L551

I'm curious why this returns the color as a string if there's only one result, but an array otherwise. Makes embedding code sort of convoluted. I didn't submit a patch because I assume there's a reason, but I just wanted to know what it is.

**Comment by NadyaNayme** [comment]
Duplicate of: #26 

Looks like the change never happened?

**Comment by Fooidge** [comment]
Haven't had time. Have a new job. I'm aware of the issue and will fix it. 

Super duper promise. 

Jordan Checkman

**Comment by ixtli** [comment]
Haha no rush! It's just that we tried using it at our job and were frustrated so we took immediately to the internet to complain!

**Comment by Fooidge** [comment]
Fixed!
