### ISSUE TITLE
Black, Grays return red shades

### ISSUE THREAD

**Issue by donnieberg** [Fooidge/PleaseJS#38]
I'm not sure if this is just me, but I tested Please.make_color with base_color gray and black, and it always returns red shades. I'm fairly new at coding so please let me know if it's me being a n00b :)

var colors = Please.make_color({
  base_color: 'gray',
  colors_returned: 20,
  format:'hex'
});

**Comment by Fooidge** [comment]
I'll look into it. There's a small bug wherein colors that translate to hue: 0 can come out as red. Might be that.

Jordan Checkman

**Comment by donnieberg** [comment]
awesome! Thank you so much for looking into it.

**Comment by Fooidge** [comment]
Latest update addresses this. Sorry for the wait :)

**Comment by donnieberg** [comment]
Awesome!! Thanks so much for fixing that :)
