### ISSUE TITLE
Do not track node_modules folder

### ISSUE THREAD

**Issue by ilovecoffee** [Fooidge/PleaseJS#39]
Hi,

It is a common practise to add a rule in the `.gitignore` file to ignore the node_modules folder. The `package.json` allows us to install all npm packages that is required by this library by executing `npm install` command. However, it is a common practise and does not mean you must remove it. If there is a valid reason, leave it to be.

P.S. Thanks for the awesome plugin!

**Comment by Fooidge** [comment]
Oops! Tiny error in gitignore, that was my intention all along. Thanks!
