### ISSUE TITLE
Support for contrasting colors

### ISSUE THREAD

**Issue by etcook** [Fooidge/PleaseJS#4]
Would be great to get the option of spitting out a harmonious contrasting color based on a color input.

**Comment by Fooidge** [comment]
I'll look into it. Based on my understanding it's a matter of finding a slightly offset complement and then inverting the value. If you wanna take a crack at it be my guest.

**Comment by etcook** [comment]
Cool - I'll research how to invert the HSV output and get back to you. Shouldn't be difficult. Do you have a preferred naming convention for contrasting colors? I'll likely just use your existing complementary function and then invert the result. Thoughts?

**Comment by Fooidge** [comment]
You could do that, but I don't think a good contrast is an exact complement.  For instance, orange and blue are famous contrasts. And you'd probably just take the distance of the value from 0 or 1 and make the contrast color have that distance from the opposing side.

**Comment by Fooidge** [comment]
Added contrast function

**Comment by etcook** [comment]
@Fooidge You got to it before I had a chance to. Thanks a million!

**Comment by Fooidge** [comment]
It's what I do ;)

Jordan Checkman
