### ISSUE TITLE
Returns an array containing sometimes the same colors

### ISSUE THREAD

**Issue by jordymeow** [Fooidge/PleaseJS#42]
The make_colors function return an array containing a few exactly same colors. When I have colors_returned = 20, I would like them to be all different since I am using this to create dynamic charts. Is this a bug?

**Comment by Fooidge** [comment]
It's not a bug, by default Please generates colors in a relatively narrow spectrum. At 20 you could potentially see some conflicts.  I may introduce the ability to generate unique colors soon, but in the meantime you might be better served by using the make_contrast or make_scheme functions. Those both help ensure fewer overlaps.
