### ISSUE TITLE
Generate constant color for an object based on a key.

### ISSUE THREAD

**Issue by s-panferov** [Fooidge/PleaseJS#48]
Hello! Thanks a lot for the amazing library!

In my project I need to create constant colors for users and chats based on their `id: Uuid`. I looked for a solution and found the PleaseJS library that is able to generate nice random colors. I have thought that I can override your random function to produce constant colors for any given `id`. But it was even easier! I just need to submit my `id` as `seed` and everything works! Cool! I use it this way:

``` typescript
Please.make_color({seed: id});
```

But I still need to monkey-patch your library because there is no way to use my own `seed` value now. Maybe we should add it? This will enable such crazy use-cases as mine is. :heart_eyes:

**Comment by csauve** [comment]
I was also looking for such a feature! I ended up generating a pseudo-random from my seed mod 360, and using that as the hue parameter.

**Comment by atomgomba** [comment]
I'm glad I've found this ticket, I had the same idea for improvement. Currently I'm using this function to do this task:

``` coffeescript
colorCache = {}

get_color = (seed) ->
    if not (seed of colorCache)
        colorCache[seed] = Please.make_color()
    return colorCache[seed]
```

But the problem is that this will increase memory usage as the `colorCache` object grows. The real solution would be to extend PleaseJS so it could generate the same color based on a value.

**Comment by tuckwat** [comment]
I also am using the hue value to generate constant colors based on a String.  I'm using the hash function here: 
http://werxltd.com/wp/2010/05/13/javascript-implementation-of-javas-string-hashcode-method/

and passing it into the hue property like so:

``` javascript
var colorSeed = Math.abs(hash) % 360;
var color = ColorUtil.make_color({golden: false,
   hue: colorSeed,
   saturation: 0.7,
   value: 0.8
});
```

Seems to be working well for my use case but only generates 360 unique colors.  Probably a good idea to use memoization if calling it frequently.

**Comment by Kronuz** [comment]
You can already do this, use the `seed` option for `make_color()`; for example:
```javascript
> Please.make_color({seed: 'some_string_must_be_string'});
[ '#72a0bf' ]
```
