### ISSUE TITLE
License is hard to find

### ISSUE THREAD

**Issue by jongalloway** [Fooidge/PleaseJS#6]
After some digging I can see that it's licensed under MIT (https://github.com/Fooidge/PleaseJS/blob/master/bower.json) but it'd be nice to see that in a license file or in readme.md or something.

**Comment by Parthchokshi** [comment]
What are you trying to say?

**Comment by Fooidge** [comment]
I'll add it in elsewhere, good call.

**Comment by Fooidge** [comment]
Added to main
