### ISSUE TITLE
Any way to fork and create website?

### ISSUE THREAD

**Issue by gtallen1187** [Fooidge/PleaseJS#73]
@Fooidge - I ***love*** this library; I use it all the time to generate soothing color palettes.

More specifically, I used the demo feature on website a lot just to generate color palettes to use for other projects.  As @billcastillo mentioned in #72, it looks as though the domain has expired and the website is no longer available.

Is it possible for me to fork this repo and stand up the website again?  Or do you have other files you used to generate the website?  If you can point me in the right direction or get me started, I'd be more than happy to stand up the website again and maintain this.

Please let me know - I really miss the site!

**Comment by monsterbrain** [comment]
How about creating a new one from scratch ?

**Comment by monsterbrain** [comment]
archived site can be seen here : https://web.archive.org/web/20160730135740/http://www.checkman.io:80/please/

**Comment by Fooidge** [comment]
Hey guys, sorry I turned off that domain. I'm sporadically working on a new version of the website/library in a private repo. If you want to make your own website using the library I'd be honored.

**Comment by monsterbrain** [comment]
I've made a small demo page using Please JS - while not that beautiful, but nevertheless thought you might want to check it out.

https://monsterbrain.github.io/pleasejs-demo/

**Comment by gtallen1187** [comment]
@monsterbrain - Thanks so much for creating this new site!  I just checked it out, it works great!

I also don't know why I didn't think of the wayback machine myself, but thanks for reminding me.

@Fooidge - Again, I really like this color library/utility, thank you very much for creating it.  My original request was for the html you used for the website, but no worries, @monsterbrain to the rescue!  While I don't have please.js implemented anywhere, i was using the website as my default tool any time i needed to randomly pick a color for something.

**Comment by zwbetz-gh** [comment]
@monsterbrain @gtallen1187 - I really like this library. Made a demo site for it as well. It gave me an excuse to play around with Github Pages https://zwbetz-gh.github.io/github-pages-deploy-pleasejs/

**Comment by monsterbrain** [comment]
> @monsterbrain @gtallen1187 - I really like this library. Made a demo site for it as well. It gave me an excuse to play around with Github Pages https://zwbetz-gh.github.io/github-pages-deploy-pleasejs/

Nice and simple. Maybe You could add a color palette with multiple colors also. will be little effort I guess 👍

**Comment by zwbetz-gh** [comment]
> > @monsterbrain @gtallen1187 - I really like this library. Made a demo site for it as well. It gave me an excuse to play around with Github Pages https://zwbetz-gh.github.io/github-pages-deploy-pleasejs/
> 
> Nice and simple. Maybe You could add a color palette with multiple colors also. will be little effort I guess 👍

Did not add color palette. But updated it to show 15 colors in a grid
