### ISSUE TITLE
Use a color library instead of reimplementing

### ISSUE THREAD

**Issue by Munter** [Fooidge/PleaseJS#9]
This code could be much easier to maintain if you pulled in css color names and color math from external well tested modules.

**Comment by Fooidge** [comment]
CSS names are standardized and well documented, and color math is as well.  Trust me, I didn't bother reinventing the wheel.

**Comment by Munter** [comment]
Just seems a waste to copy/paste boilerplate like this into every color manipulating library out there.

**Comment by Fooidge** [comment]
Dependency free is a big goal for me, especially when the size of the library minified+gzipped is so tiny.
